FROM amsterdam/docker_python:latest
MAINTAINER datapunt@amsterdam.nl

# Install api service in /app folder
WORKDIR /app

# Install required Python packages
COPY requirements.txt /app/
RUN pip3 install --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org --no-cache-dir -r requirements.txt
RUN rm requirements.txt

# Copy gob StUF module
COPY gobstuf gobstuf

# Remove gobcore tests
RUN rm -rf /app/src/gobcore/tests
RUN rm -rf /app/src/flask-audit-log/tests

# Copy tests
COPY tests tests
COPY .flake8 .flake8
COPY test.sh test.sh

# Copy jenkins files
COPY .jenkins /.jenkins
